### ISSUE TITLE
ERROR PHP WARNING: imagecreatefrompng(): gd-png: libpng warning: iCCP: cHRM chunk does not match sRGB in file: D:\cacti\apache\htdocs\cacti\plugins\weathermap\lib\WeatherMap.functions.php on line: 477

### ISSUE THREAD

**Issue by MSS970** [thurban/plugin_weathermap#92]
Dear Team,
I appreciate your support and advice on the following:

15-Feb-2023 20:27:55 - ERROR PHP WARNING: imagecreatefrompng(): gd-png: libpng warning: iCCP: cHRM chunk does not match sRGB in file: D:\cacti\apache\htdocs\cacti\plugins\weathermap\lib\WeatherMap.functions.php on line: 477

please can you advise how to fix the above?

Much appreciated.

**Comment by MSS970** [comment]
PHP 7.x is in use.
Cacti 1.2.3
Weathermap 1.0 - develop.

**Comment by TheWitness** [comment]
From this repo?

**Comment by TheWitness** [comment]
You need to mogrify your png files.  Follow the instructions here.

https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile

**Comment by TheWitness** [comment]
All the base images that come prepackaged in the plugin already have this done to them.

**Comment by MSS970** [comment]
Much appreciated

**Comment by chiessijlb** [comment]
I had the same error. I'm using **DomPDF 2.0.3** with **PHP 8.0.25**.
The issue is clearly with PNG image files, but it happens only when using DomPDF, the same image is used in other PHP modules and no error is raised.

The PDF file I'm creating with DomPDF has a PNG image in the header. When creating it, I receive the following message:
* "Error 2: imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile"

If I make reference to a JPG image, the error doesn't occur. That is pretty normal, as the function `imagecreatefrompng()` is not called.

If I make reference to a PNG image without transparency, I receive the following two error messages:
* "Error 2: imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile"
* "Error 2: imagecreatefrompng(): gd-png: libpng warning: iCCP: cHRM chunk does not match sRGB"

**Note:** the function `imagecreatefrompng()` call on cPDF.php class is already referenced with "`@`".

**Some considerations:**
If the image is loaded by the program, only through the code developed by the programmer, it's easy to resolve, just convert the PNG image to JPG and change its reference on the code to load the JPG image. But when the image is uploaded through systems directly by the users, it's more complex to control. I think a temporary solution is, when uploading the image file through the system, convert the PNG image to JPG. But if the transparency is required, that solution doesn't work.
